DROP TABLE IF EXISTS TELEVISIONSHOW;
CREATE TABLE TELEVISIONSHOW (
showname VARCHAR(50) PRIMARY KEY,
showdescription VARCHAR(50) NOT NULL,
showday VARCHAR(50) NOT NULL,
showtime VARCHAR(50) NOT NULL
);